apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      httpMethod: GET

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        # hex trace_id → Tempo jump
        - name: TraceID
          matcherRegex: 'trace_id="?([a-fA-F0-9]{32})"?'
          datasourceUid: Tempo
          url: $${__value.raw}
        # (optional) decimal dd_trace_id 표시
        - name: DDTraceID
          matcherRegex: 'dd_trace_id="?([0-9]{1,20})"?'
          url: ""
