server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    pipeline_stages:
      - multiline:
          firstline: '^\S'
      - match:
          selector: '{container_name="demo-app"}'
          stages:
            - regex:
                expression: '(?i)(api[_-]?key|authorization|password)=(\S+)'
            - replace:
                expression: '(?i)(api[_-]?key|authorization|password)=(\S+)'
                replace: '$1=*****'
