global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: demo-app
    static_configs:
      - targets: ['demo-app:8080']
    metric_relabel_configs:
      - source_labels: [pod, container, instance]
        regex: ".*"
        action: labeldrop
